development:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_development
  user: octo
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  user: octo
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell
  pool: 10
  min_messages: warning
  user: octo
  password: 123456
